package com.evertec.newarchitecture.api.model.customer;

import java.io.Serializable;

public enum CustomerInteractionEventType implements Serializable {

	ADD_SMS_ALERTS, INFO_SMS_ALERTS, UPDATE_SMS_ALERTS, DELETE_SMS_ALERTS, SIGNON_SUCCESS, PASSWORD_VALIDATION_SUCCESS, PASSWORD_VALIDATION_FAIL, PASSWORD_VALIDATION_BLOCK, PASSWORD_RESET_SUCCESS, PASSWORD_RESET_FAIL, PASSWORD_RESET_BLOCK, CHANGE_PASSWORD_SUCCESS, CHANGE_PASSWORD_FAIL, CHANGE_EMAIL_SUCCESS, CHANGE_EMAIL_FAIL, CREATE_SMS_PROFILE_SUCCESS, CREATE_SMS_PROFILE_FAIL, CHANGE_SMS_PHONE_SUCCESS, CHANGE_SMS_PHONE_FAIL, DELETE_SMS_PROFILE_SUCCESS, DELETE_SMS_PROFILE_FAIL, CHANGE_RSA_QUESTIONS_SUCCESS, CHANGE_RSA_QUESTIONS_FAIL, CHANGE_ALERTS_SUCCESS, CHANGE_ALERTS_FAIL, RSA_ENROLL_SUCCESS, RSA_ENROLL_FAIL, VALIDATE_ACCOUNT_INF_FAIL, VALIDATE_ACCOUNT_INF_SUCCESS, VALIDATE_ACCOUNT_INF_BLOCK, ACCEPT_TERMS, VALIDATE_DOB_FAIL, VALIDATE_DOB_SUCCESS, CHANGE_BIRTHDATE_SUCCESS, CHANGE_BIRTHDATE_FAIL, VALIDATE_RSA_QUESTION_SUCCESS, VALIDATE_RSA_QUESTION_FAIL, VALIDATE_RSA_QUESTION_BLOCK, CHANGE_USERNAME_SUCCESS, CHANGE_USERNAME_FAIL, INVALID_USERNAME, SIGNON_ATTEMPT_WHILE_PWD_BLOCKED, SIGNON_ATTEMPT_WHILE_RSA_BLOCKED, SIGNON_ATTEMPT_WHILE_RSA_DENIED,

	MBOP_SIGNON_SUCCESS, MBOP_PASSWORD_VALIDATION_SUCCESS, MBOP_PASSWORD_VALIDATION_FAIL, MBOP_PASSWORD_VALIDATION_BLOCK, MBOP_PASSWORD_RESET_SUCCESS, MBOP_PASSWORD_RESET_FAIL, MBOP_PASSWORD_RESET_BLOCK, MBOP_CHANGE_PASSWORD_SUCCESS, MBOP_CHANGE_PASSWORD_FAIL, MBOP_CHANGE_RSA_QUESTIONS_SUCCESS, MBOP_CHANGE_RSA_QUESTIONS_FAIL, MBOP_RSA_ENROLL_SUCCESS, MBOP_RSA_ENROLL_FAIL, MBOP_VALIDATE_ACCOUNT_INF_FAIL, MBOP_VALIDATE_ACCOUNT_INF_SUCCESS, MBOP_VALIDATE_ACCOUNT_INF_BLOCK, MBOP_ACCEPT_TERMS, MBOP_ACCEPT_PREMIA_TERMS, MBOP_ACCEPT_SHARE_INFO, MBOP_DENIED_PREMIA_TERMS, MBOP_DENIED_SHARE_INFO, MBOP_VALIDATE_DOB_FAIL, MBOP_VALIDATE_DOB_SUCCESS, MBOP_VALIDATE_RSA_QUESTION_SUCCESS, MBOP_VALIDATE_RSA_QUESTION_FAIL, MBOP_VALIDATE_RSA_QUESTION_BLOCK, MBOP_INVALID_USERNAME, MBOP_SIGNON_ATTEMPT_WHILE_PWD_BLOCKED, MBOP_SIGNON_ATTEMPT_WHILE_RSA_BLOCKED, MBOP_SIGNON_ATTEMPT_WHILE_RSA_DENIED, MBOP_DEACTIVATED, MBOP_ACTIVATED, MBOP_PASSWORD_UNBLOCK, MBOP_RSA_QUESTION_UNBLOCK, MBOP_OFERTAS_ACCEPTANCE,

	PAYMENT_SEND, PAYMENT_MODIFY, PAYMENT_DELETE, TRANSFER_SEND, TRANSFER_MODIFY, TRANSFER_DELETE, PAYEE_ADD, PAYEE_DELETE,

	OCC_PAYEE_ADD, OCC_CUSTOMER_PAYEE_ADD, OCC_CUSTOMER_PMT_ADD, OCC_PAYMENT_ADD,

	// mpicado, cibp-2204
	VIEW_EBILL, VIEW_ESTATEMENT,
	// mpicado, cibp-2205
	VIEW_CHECKIMAGE, VIEW_PDF_STMT, VIEW_PDF_STMT_SHOW,

	PASSWORD_UNBLOCK, RSA_QUESTION_UNBLOCK,

	UPDATE_BANKING_ENT, UPDATE_BANKING_ENT_FAIL, UPDATE_EBILL_ENT, UPDATE_EBILL_ENT_FAIL, UPDATE_EBPP_CAN, UPDATE_EBPP_CAN_FAIL,

	REMOTE_DEPOSIT_SUCCESS, REMOTE_DEPOSIT_FAIL, FIS_ENROLLMENT_SUCCESS, FIS_ENROLLMENT_FAIL, ATHM_ENROLL_SUCCESS, ATHM_ENROLL_FAIL, ATHM_XFER_SUCCESS, ATHM_XFER_FAIL,

	DCI_CUSTOMER_CREATED, DCI_ANSWERS_COMPLETED, DCI_ERROR_REMOVING_IDA_CODE, DCI_ERROR_REMOVING_NO_POST, DCI_ERROR_INSERT_IDA_CODE, DCI_ERROR_INSERT_NO_POST,

	ACCEPTED_DOCUMENTS, ACCEPTED_UNICA_OFFER, ACCEPT_UNICA_OFFER_ERROR,

	ESIGN_ACCOUNT_REGISTRATION, ESIGN_ACCOUNT_WARNING_REGISTRATION, ESIGN_FLAG_ADDED, ESIGN_FLAG_REMOVED,

	// 1886
	UPDATE_ENROLL_ACCT, UPDATE_ENROLL_ACCT_FAIL, UPDATE_ENROLL_ACCT_BLOCK,

	//Incident 2712087
	ERROR_ENROLL_ACCT,
	//MLA
	UPDATE_MLA_ESTMT_STATUS,
	
	MIBANCO_COMERCIAL_ACCEPTANCE, 
	
	//MBSFE-151 adding more logs for 1886
	RETRIEVING_ACCOUNTS, RETRIEVING_FILTERED_ACCOUNTS, 
	
	//MBSFE-145 adding logs ebill & statemnts activate/desactivate
	EBPP2_UPDATE_EBILLS_STATUS,
	EBPP2_UPDATE_STATEMENT_STATUS,
	
	LISTING_EBILLS_AND_STAMT_STATUS,
	
	OOB_REMOVED,
	
	MOBILE_CASH_TR_SUBMIT,
	MOBILE_CASH_TR_ASSIGN_ATM,
	MOBILE_CASH_TR_CANCEL,
	
	//MBSD-314 audit Log OOB
	ENROLLMENT_OOB, ENROLLMENT_SMS_OOB,	ENROLLMENT_VOICE_OOB, REGISTER_SECONDARY_PHONE_OOB, DEACTIVATE_OOB, REMOVE_BY_RECOVERY_CODE_OOB, CHALLENGE_SMS_OOB, CHALLENGE_VOICE_OOB,
	FREQUENCY_ALWAYS_OOB, FREQUENCY_AS_REQUIRED_OOB,
	
	//MBMT-335 Logs for Mobile Wallet Tokenization
	TOKENIZATION_ACTIVATION_SUCCESS, TOKENIZATION_ACTIVATION_FAILED
	;
	
	public static Object fromString(String string) {
		return CustomerInteractionEventType.valueOf(string);
	}

	public String toString(Object o) {
		return o.toString();
	}
}